version: "3.8"
services:
  gymenv:
    build:
      context: .
    environment:
      DISPLAY: host.docker.internal:0.0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./learning_rule.py:/app/learning_rule.py # Mount learning_rule.py directly
    devices:
      - /dev/dri
    entrypoint: ["python3"]
    command: ["learning_rule.py"] # Default script; override as needed